# Generated by Django 6.0.7 on 2026-09-06 22:31

from django.conf import settings
from django.db import migrations, models

import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("video_requests", "0008_add_todo_status_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="assignees",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_todos", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="creator",
            field=models.ForeignKey(
                on_delete=models.SET(common.models.get_sentinel_user),
                related_name="created_todos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
