/* tslint:disable */
/* eslint-disable */
/**
 * BSS Request Manager API
 * REST API for Workflow Support System for managing video shooting, filming and live streaming requests of Budavári Schönherz Stúdió.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kecskemety.oliver@simonyi.bme.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SessionUser
 */
export interface SessionUser {
  /**
   *
   * @type {string}
   * @memberof SessionUser
   */
  avatar_url: string | null;
  /**
   *
   * @type {Array<string>}
   * @memberof SessionUser
   */
  groups: Array<string>;
  /**
   *
   * @type {number}
   * @memberof SessionUser
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof SessionUser
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof SessionUser
   */
  role: string;
}
