# Generated by Django 6.0.7 on 2026-09-05 21:32

import django.core.serializers.json
import phonenumber_field.modelfields
from django.db import migrations, models

import common.models


def copy_profiles_to_users(apps, schema_editor):
    User = apps.get_model("common", "User")
    UserProfile = apps.get_model("common", "UserProfile")
    User.objects.bulk_update(
        (
            User(
                pk=profile.user_id,
                avatar=profile.avatar,
                phone_number=profile.phone_number,
            )
            for profile in UserProfile.objects.all().iterator()
        ),
        ["avatar", "phone_number"],
    )


def copy_users_to_profiles(apps, schema_editor):
    User = apps.get_model("common", "User")
    UserProfile = apps.get_model("common", "UserProfile")
    UserProfile.objects.bulk_create(
        UserProfile(user_id=user.pk, avatar=user.avatar, phone_number=user.phone_number)
        for user in User.objects.all().iterator()
    )


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_move_user_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                validators=[common.models.validate_avatar],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
        migrations.RunPython(copy_profiles_to_users, copy_users_to_profiles),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
