# Generated by Django 6.0.7 on 2026-09-06 22:15

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("common", "0006_set_unusable_password_on_system_accounts"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("email", ""), _negated=True),
                name="unique_user_email",
                violation_error_message="E-mail address already in use.",
            ),
        ),
    ]
