# Generated by Django 6.0.7 on 2026-09-06 22:31

from django.conf import settings
from django.db import migrations, models

import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_add_unique_user_email_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ban",
            name="creator",
            field=models.ForeignKey(
                on_delete=models.SET(common.models.get_sentinel_user),
                related_name="created_bans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
