# Generated by Django 6.0.8 on 2026-09-08 09:02

import django.core.serializers.json
import phonenumber_field.modelfields
from django.db import migrations, models

import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_fix_user_related_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                validators=[common.models.validate_avatar],
                verbose_name="avatar",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="phone number"
            ),
        ),
    ]
